<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php

$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$outofstock_helper = $this->helper('Solwin\Soldout\Helper\Data');
$outofstockEnable = $outofstock_helper->getConfigValue('outofstock_product/outofstockproduct/enableoutofstock');
$outofstockLabelImage = $outofstock_helper->getConfigValue('outofstock_product/outofstockproduct/showstock_label_image');
$outofstockTitle = $outofstock_helper->getConfigValue('outofstock_product/outofstockproduct/titleoutofstock');
$outofstockImage = $outofstock_helper->getConfigValue('outofstock_product/outofstockproduct/imageoutofstock');
$imageUrl = $outofstock_helper->getMediaUrl() . 'outofstockimage/' . $outofstockImage;
$outofstockPositionLabel = $outofstock_helper->getConfigValue('outofstock_product/outofstockproduct/showstock_position_label');
$outofstockPositionImage = $outofstock_helper->getConfigValue('outofstock_product/outofstockproduct/showstock_position_image');
$outofstockImageHeight = $outofstock_helper->getConfigValue('outofstock_product/outofstockproduct/imageheightoutofstock');
$outofstockImagewidth = $outofstock_helper->getConfigValue('outofstock_product/outofstockproduct/imagewidthoutofstock');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currency = $currencysymbol->getStore()->getCurrentCurrencyCode();


?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">

        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="music music indexproduct col-md-3 col-sm-6 col-xs-12">' : '</li>

                                    
                                            
<li class="music music  col-md-3 indexproduct col-sm-6 col-xs-12">' ?>
                <?php
                $productImage = $block->getImage($_product, $image);

                ?>





                <div class="newproduct-sep">
                <div class="newproduct-thumb">
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                        <?php echo $productImage->toHtml(); ?>
                        <?php
                        if (!$_product->getIsSalable()):
                            if ($outofstockEnable) {
                                if ($outofstockLabelImage == 'label') {
                                    ?>
                                    <div class="out-of-stock-wrapper <?php echo $outofstockPositionLabel; ?>"><?php echo $outofstockTitle; ?></div>
                                    <?php
                                }
                                if ($outofstockLabelImage == 'image') {
                                    if ($outofstockImage) {
                                        ?>
                                        <div class="out-of-stock-wrapper <?php echo $outofstockPositionImage; ?>"><img src="<?php echo $imageUrl; ?>" height="<?php echo $outofstockImageHeight; ?>" width="<?php echo $outofstockImagewidth; ?>"/></div>
                                        <?php
                                    }
                                }
                            }
                        endif;
                        ?>
                    </a>

                </div>
                <div class="newproduct-title-price">
                <div class="hover-layers">
                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                    <a href="#"  style="float: right;margin: 8px 19% -19% 0;"
                       class="action towishlist"
                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                       data-action="add-to-wishlist"
                       role="button">
                        <i class="fas fa-heart fa-2x"></i>
                    </a>
                    <?php
                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId()])
                    ?>
                    <button class="action tocart"
                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                        <i class="fas fa-cart-plus fa-2x"></i>
                    </button>
                    <!--                                        <form data-role="tocart-form" action="--><?php ///* @escapeNotVerified */ echo $postParams['action']; ?><!--" method="post">-->
                    <!--                                            <input type="hidden" name="product" value="--><?php ///* @escapeNotVerified */ echo $postParams['data']['product']; ?><!--">-->
                    <!--                                            <input type="hidden" name="--><?php ///* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?><!--" value="--><?php ///* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?><!--">-->
                    <!---->
                    <!---->
                    <!--                                            <button type="submit"-->
                    <!--                                                    data-mage-init='{"redirectUrl":{"url":"--><?php ///* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?><!--"}}'-->
                    <!--                                                    title="--><?php //echo $block->escapeHtml(__('Add to Cart')); ?><!--"-->
                    <!--                                                    class="action tocart">-->
                    <!--                                                <i class="fas fa-cart-plus fa-2x"></i>-->
                    <!--                                            </button>-->
                    <!--                                        </form>-->


                    </div>
                    <div class="newproduct-price">


                        <?php
                        if($_product->getFinalPrice() < $_product->getPrice()){
                            //had a discount

                            ?>
                            <ins>
													<span class="woocommerce-Price-amount amount">
														<span class="woocommerce-Price-currencySymbol"><?php echo $currency; ?> </span>
                                                        <?php
                                                        if($_product->getTypeId()=='bundle')
                                                        {
                                                            $bundleObj=$_product->getPriceInfo()->getPrice('final_price');
                                                            echo ($bundleObj->getMinimalPrice());// For min price
                                                        }
                                                        else
                                                        {
                                                            echo ($_product->getFinalPrice(1))+0;
                                                        }
                                                        ?>
                                                    </span>
                            </ins>
                            <del>
													<span class="woocommerce-Price-amount amount">
														<span class="woocommerce-Price-currencySymbol"><?php echo $currency; ?>  </span><?php echo $_product->getPrice()+0; ?></span>
                            </del>
                        <?php } else { ?>
                            <ins>
													<span class="woocommerce-Price-amount amount">
														<span class="woocommerce-Price-currencySymbol"><?php echo $currency; ?> </span>
                                                        <?php
                                                        if($_product->getTypeId()=='bundle')
                                                        {
                                                            $bundleObj=$_product->getPriceInfo()->getPrice('final_price');
                                                            echo ($bundleObj->getMinimalPrice());// For min price
                                                        }
                                                        else
                                                        {
                                                            echo ($_product->getFinalPrice(1))+0;
                                                        }
                                                        ?>
                                                    </span>
                            </ins>
                        <?php } ?>
                    </div>
                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                    <div class="newproduct-title"><?php echo $_productNameStripped; ?></div>

                    <?php if ($showDescription): ?>

                        <div class="cff"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?> <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                                                                                                                                                                class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a></div>



                    <?php endif; ?>

                    </div>
                    <div class="clear"></div>
                    </div>
                    <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
<!--    --><?php //echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
            }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
