<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>


<div class="copyright-wrapper">
    <div class="container">
        <div class="copyright-txt">
            <em>© Copyright 2018
                <a href="#">Lensme .</a> All Rights Reserved</em>
        </div>
        <div class="design-by">
            <em>Design by
                <a href="http://www.mawaqaa.com" target="_blank">Mawaqaa</a>
            </em>
        </div>
    </div>
    <div class="clear"></div>
</div>


</div>