<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
// if ($block->hasRequiredOptions()) {
//     $required = ' data-hasrequired="' . __('* Required Fields') . '"';
// }
// ?>

<?php
$_product = $this->getProduct(); $_productName = $_product->getName(); $_product_des = $_product->getShortDescription();  
?>

    

    <div class="product-options-wrapper" id="product-options-wrapper" <?=/* @escapeNotVerified */ $required ?>>
        <div class="fieldset" tabindex="0">
            <?= $block->getChildHtml('', true) ?>
        </div>

    </div>

          
